AY2223S2-CS2113-T13-4/tp

docs/AboutUs.md

Edited AboutUs.md to reflect my information

branch irving-AboutUs

---

docs/AboutUs.md

Edited AboutUs.md to reflect my information

branch YiXuan-AboutUs

---

docs/AboutUs.md

Edited About.Us.md to reflect my information

brach wanlin-AboutUs

---

src/main/java/seedu/apollo/module/Module.java

Created Module base class with moduleName and moduleCode attributes for MVP

Created Module base class

---

src/test/java/seedu/apollo/ParserTest.java

Add tests for parseDateTime
Add tests for parseDeadline

Partial JUnit testing for Parser

---

src/main/java/seedu/apollo/Ui.java
src/main/java/seedu/apollo/command/ListModuleCommand.java
src/main/java/seedu/apollo/module/ModuleList.java

Create a ModuleList class and ListModuleCommand class. Create a method in Ui to print module list.

ModuleList Class

---

src/main/java/seedu/apollo/Parser.java
src/main/java/seedu/apollo/Ui.java
src/main/java/seedu/apollo/command/AddModuleCommand.java
src/main/java/seedu/apollo/exception/EmptyAddModException.java
src/main/java/seedu/apollo/exception/EmptyDelModException.java

Exception Handling for both delete and add command.

Add Exception Handling for addmod and delmod commands

---

src/main/java/seedu/apollo/Parser.java
src/main/java/seedu/apollo/command/AddModuleCommand.java
src/main/java/seedu/apollo/command/DeleteModuleCommand.java
src/main/java/seedu/apollo/module/ModuleList.java
src/test/java/seedu/apollo/module/ModuleListTest.java

Update find method for ModuleList

---

src/main/java/seedu/apollo/command/AddModuleCommand.java
src/main/java/seedu/apollo/module/ModuleList.java

Sort NUS module list alphabetically as per NUS Edurec standards.

---

.gitignore
src/main/java/seedu/apollo/Apollo.java
src/main/java/seedu/apollo/Storage.java
src/main/java/seedu/apollo/command/AddCommand.java
src/main/java/seedu/apollo/command/AddModuleCommand.java
src/main/java/seedu/apollo/command/DeleteModuleCommand.java
src/main/java/seedu/apollo/command/ModifyCommand.java
src/test/java/seedu/apollo/UiTest.java
text-ui-test/EXPECTED.TXT

Added Functionality of saving ModuleList to hard drive

---

src/test/java/seedu/apollo/UiTest.java

Update JUnit tests to fix build gradle error

---

src/main/java/seedu/apollo/command/module/AddModuleCommand.java
src/main/java/seedu/apollo/command/module/DeleteModuleCommand.java
src/main/java/seedu/apollo/command/module/ListModuleCommand.java
src/main/java/seedu/apollo/command/task/DateCommand.java

Help check the logging and assertions

Add Assertions and Logging for module commands

---

src/main/java/seedu/apollo/task/Task.java
src/main/java/seedu/apollo/ui/Ui.java
src/test/java/seedu/apollo/ParserTest.java

Update datetime formatter to fix formatting bug

---

src/main/java/seedu/apollo/task/TaskList.java
src/main/java/seedu/apollo/ui/Ui.java

Update findTasks methods to use streams

---

src/main/java/seedu/apollo/module/Module.java

Update backend NUSMods data

---

src/main/java/seedu/apollo/command/module/AddModuleCommand.java
src/main/java/seedu/apollo/exception/module/LessonAddedException.java
src/main/java/seedu/apollo/module/Module.java
src/main/java/seedu/apollo/ui/Ui.java

Add checking for whether lesson type exists already for module

---

docs/DeveloperGuide.md
src/main/java/seedu/apollo/command/module/AddModuleCommand.java
src/main/java/seedu/apollo/storage/Storage.java

Finish up AddModule implementation to DG

Add second half of AddModule implmentation to DG

---

src/main/java/seedu/apollo/command/module/AddModuleCommand.java
src/main/java/seedu/apollo/command/module/DeleteModuleCommand.java
src/main/java/seedu/apollo/storage/Storage.java
src/main/java/seedu/apollo/ui/Ui.java
src/main/java/seedu/apollo/utils/LoggerInterface.java

Unpolished implementation. Closes #111

Add functionality to delete module lessons

---

src/main/java/seedu/apollo/calendar/Calendar.java

Add chronological sorting for lessons in calendar

---

src/main/java/seedu/apollo/command/Command.java
src/main/java/seedu/apollo/command/module/AddModuleCommand.java
src/main/java/seedu/apollo/command/module/DeleteModuleCommand.java
src/main/java/seedu/apollo/command/module/ShowModuleCommand.java
src/main/java/seedu/apollo/ui/Ui.java
text-ui-test/EXPECTED.TXT
text-ui-test/input.txt

Add ability to show available lessons for a particular lesson type of a module

---

src/main/java/seedu/apollo/task/Deadline.java
src/main/java/seedu/apollo/task/Event.java
src/main/java/seedu/apollo/task/TaskList.java
src/test/java/seedu/apollo/task/DeadlineTest.java
src/test/java/seedu/apollo/task/EventTest.java
src/test/java/seedu/apollo/task/ToDoTest.java

Full JUnit coverage for ToDo, Deadline, Event

Add JUnit tests

---

src/main/java/seedu/apollo/command/module/AddModuleCommand.java
src/main/java/seedu/apollo/ui/Ui.java
src/main/java/seedu/apollo/utils/DayTypeUtil.java

Added warning message for when two lessons in timetable clash

---

src/test/java/seedu/apollo/command/task/ListCommandTest.java

Add 100% coverage for ListCommand

---

src/main/java/seedu/apollo/command/task/AddCommand.java
src/main/java/seedu/apollo/ui/Ui.java
src/main/java/seedu/apollo/utils/DayTypeUtil.java
src/main/java/seedu/apollo/utils/LessonTypeUtil.java
text-ui-test/EXPECTED.TXT

Add event module clash warning functionality

---

src/main/java/seedu/apollo/task/TaskList.java

Not slay that my stuff got overwritten

Add assertions in TaskList methods

---

text-ui-test/EXPECTED.TXT
text-ui-test/input.txt

Update backend data with current semester data

---

src/main/java/seedu/apollo/command/task/AddCommand.java

Fixed bug for event and lessons clash 

---

src/main/java/seedu/apollo/command/module/ShowModuleCommand.java
src/main/java/seedu/apollo/command/task/AddCommand.java
src/main/java/seedu/apollo/module/Timetable.java
src/main/java/seedu/apollo/ui/Ui.java

Update UI Message for modules which are not in current semester.

---

src/main/java/seedu/apollo/command/task/AddCommand.java
src/main/java/seedu/apollo/task/Deadline.java
src/main/java/seedu/apollo/ui/Ui.java

Can someone suggest how to remove the error from checkstyle? closes #193

Create new error message for invalid date

---

src/main/java/seedu/apollo/command/module/ShowModuleCommand.java

Fixed ShowMod bug where double print message occurs

---

src/main/java/seedu/apollo/command/task/ModifyCommand.java
src/main/java/seedu/apollo/ui/Ui.java

Constrain marking and unmarking to be done once

---

docs/UserGuide.md
src/main/java/seedu/apollo/ui/Ui.java

Fix #196 
Also fix #190 UG bug

Improve format for weekly schedule

---

src/main/java/seedu/apollo/exception/utils/DuplicateModuleInTextFileException.java
src/main/java/seedu/apollo/storage/Storage.java
src/main/java/seedu/apollo/ui/Ui.java

Add alert for duplicate module in moduleData.txt

---

src/main/java/seedu/apollo/ui/Ui.java

Update week command to show class number

---

src/main/java/seedu/apollo/command/module/AddModuleCommand.java
src/main/java/seedu/apollo/command/task/AddCommand.java

Improve code quality based on Code Review comments

---

docs/team/aatmika.md
src/main/java/seedu/apollo/command/task/AddCommand.java
text-ui-test/EXPECTED.TXT

Branch fix bug

---

src/main/java/seedu/apollo/command/utils/AddModHelpCommand.java
src/main/java/seedu/apollo/command/utils/DeleteModHelpCommand.java
src/main/java/seedu/apollo/command/utils/ExitHelpCommand.java
src/main/java/seedu/apollo/command/utils/ListModuleHelpCommand.java
src/main/java/seedu/apollo/command/utils/ShowModHelpCommand.java
src/main/java/seedu/apollo/command/utils/SpecifiedAidHelpCommand.java
src/main/java/seedu/apollo/command/utils/WeekHelpCommand.java
src/main/java/seedu/apollo/ui/Parser.java
src/main/java/seedu/apollo/ui/Ui.java
text-ui-test/EXPECTED.TXT
text-ui-test/input.txt

Implement specified help commands #219

---

docs/UserGuide.md
src/main/java/seedu/apollo/ui/Parser.java
src/main/java/seedu/apollo/ui/Ui.java
src/test/java/seedu/apollo/ParserTest.java
src/test/java/seedu/apollo/command/task/AddCommandTest.java
text-ui-test/EXPECTED.TXT
text-ui-test/input.txt

Standardise event and deadline command format

---

src/main/java/seedu/apollo/command/module/ListModuleWithLessonCommand.java
src/main/java/seedu/apollo/exception/module/EmptyLessonTypesInTimetable.java
src/main/java/seedu/apollo/exception/module/ModuleNotAddedException.java
src/main/java/seedu/apollo/ui/Ui.java

Caught exceptions when no classes are being added to a module and listmod is called.

Catch exceptions for ListMod with lesson types

---

src/main/java/seedu/apollo/module/Timetable.java
src/main/java/seedu/apollo/ui/Ui.java
text-ui-test/EXPECTED.TXT

Add week enhancement

---

src/main/java/seedu/apollo/ui/Ui.java
src/test/java/seedu/apollo/ParserTest.java
src/test/java/seedu/apollo/UiTest.java
src/test/java/seedu/apollo/command/task/SpecificHelpCommandTest.java

Help command updates

---

docs/DeveloperGuide.md
docs/UserGuide.md

Add final documentation
